name: Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup and use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install the dependencies
      run: npm ci
    - name: Build the website
      run: npm run build --if-present
      env:
        CI: true
    - name: Copy website files to production server
      uses: appleboy/scp-action@master
      with:
        host: relivehelbreath.com
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "dist"
        target: "~/www"
    - name: Make the new website files current
      uses: appleboy/ssh-action@master
      with:
        host: relivehelbreath.com
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: sudo chown www-data:www-data www && sudo cp -r www/* /var/www/
